opentelemetry/ecs-ec2/README.md

- updated default image
- updated default image name in cofig

Update default image name for ECS EC2

---

opentelemetry/ecs-ec2/template.yaml

- updated default otel config
- added volume mount for /var/run/docker.sock

update default otel conf

---

prometheus/ecs-ec2/autodiscovery/README.md

This PR adds additional information to the Prometheus Autodiscovery Readme based on user feedback

[CDS-385] update prometheus autodiscovery readme 

---

.github/workflows/synchronizing.yaml
replace_template.sh

create an action to sync this repo with the integration-definitions repo. The action will check if there were a change in a template file, and then change the template according to the requirements in the integration-definitions repo with the replace_template script.

Create sync action and replace_template file

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/components.md
opentelemetry/ecs-ec2/template.yaml

This PR updates the current ECS-EC2 otel deployment solution.
- Added embedded default templates for metrics, logs and traces
-  Updated documentation
- Updated Image for ECS-EC2 otel deployments to the [coralogix-otel-collector](https://hub.docker.com/r/coralogixrepo/coralogix-otel-collector) image.
Fixes #

[cds-305] Update ECS-EC2 cloudformation template

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose/template.yaml

Update the action to work with firehose integration.
change in firehose integration CoralogixApiKey parameter name to ApiKey
Fixes #
create a private environment to test the action

update sync action to work with firehose integration and trigger the action[CDS-307]

---

aws-integrations/firehose/README.md
aws-integrations/firehose/parameters.json

Change CoralogixApiKey parameter to ApiKey in the readme and parameters files.

Change CoralogixApiKey parameter name to ApiKey

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/README.md
aws-integrations/firehose/template.yaml

Change dynamicMetaData param to only logs
Locally ran the CF template

dynamicMetadata change set

---

opentelemetry/ecs-ec2-windows/CHANGELOG.md
opentelemetry/ecs-ec2-windows/README.md
opentelemetry/ecs-ec2-windows/template.yaml
opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/components.md

This PR adds an example for ECS EC2 Windows for collecting metrics

Added EC2 EC2 Windows Example for metrics Collection

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

- updated readme
- updated changelog
- added otel collector metrics to embedded otel config
- fix port mappings

Add Collector Metrics to ECS-EC2 otel implementation

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

log.file.path removal from coralogix exporter subsystem attributes
Fixes #

log.file.path removal from coralogix exporter subsystem attributes

---

.github/workflows/synchronizing.yaml

Just a echo in synchronizing.yaml to check on the value.
- [*] This change does not affect any particular component (e.g. it's readme or docs change)

troubleshoot gh actions branch name

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose/template.yaml

fix an issue with the sync action
Fixes #

Guyrenny patch 1

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/README.md
aws-integrations/firehose/parameters.json
aws-integrations/firehose/template.yaml

Added Custom domain and OpenTelemetry070_WithAggregations option
Locally

Custom domain & OpenTelemetry070 with Aggregations

---

.github/workflows/synchronizing.yaml

Fix for gh actions
not yet, needs to be merged-pushed

fixed synchonize gh-action, backlog from firehose

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/template.yaml

Just descriptive changes to trigger the GH script

Firehose backlog changes - Sync PR

---

aws-integrations/firehose/template.yaml

add test line check

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/README.md
aws-integrations/firehose/template.yaml

Test change for testing PR Sync action

test change update

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/README.md
aws-integrations/firehose/template.yaml

added cf text change to trigger
None, text only

added cf text change to trigger

---

aws-integrations/firehose/template.yaml

This must create a pr hopefully
Locally

Test Pr Sync 

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose/template.yaml

Test pr branch

---

aws-integrations/firehose/template.yaml

test change text

---

.github/workflows/synchronizing.yaml

hopefully this works to fix the sync script
- [] I have updated the relevant component changelog(s)
- [] This change does not affect any particular component (e.g. it's readme or docs change)

fixes to action syncs

---

aws-integrations/firehose/template.yaml

setoff change

---

aws-integrations/firehose/template.yaml

test sync script

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/template.yaml

actions update annotations test

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose-logs/CHANGELOG.md
aws-integrations/firehose-logs/README.md
aws-integrations/firehose-logs/template.yaml

Update var dynamicfromfields

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose-metrics/template.yaml
scripts/replace_template.sh

pr gh actions changes for the replace template and pr-name generate
Locally in separate repo

fix for custom domain and pr-name

---

.github/workflows/synchronizing.yaml
aws-integrations/firehose-metrics/template.yaml

update sync if condition
Locally at separate repo

Update sync branchname

---

scripts/replace_template.sh

Change `CoralogixRegion` to `CoralogixDomain` in the `IntegrationStatusNotifier` resource

fix bug in replace_template.sh

---

aws-integrations/firehose-metrics/CHANGELOG.md
aws-integrations/firehose-metrics/README.md
aws-integrations/firehose-metrics/template.yaml

remove CloudWatch_Metrics_JSON from an option of integration type metrics
non-functional change but code changes

remove CloudWatch_Metrics_JSON

---

scripts/replace_template.sh

Fix issue with coralogixApiKey [CDS-867]

---

coralogix-eventbridge-policy/CHANGELOG.md
coralogix-eventbridge-policy/README.md
coralogix-eventbridge-policy/template.yaml

[VTX-3815](https://coralogix.atlassian.net/browse/VTX-3815)
Improving Gerard's unmerged PR https://github.com/coralogix/cloudformation-coralogix-aws/pull/99
[VTX-3815]: https://coralogix.atlassian.net/browse/VTX-3815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add CF template for assigning EventBridge policy

---

.github/CODEOWNERS

Remove platform from code owners

---

coralogix-eventbridge-policy/CHANGELOG.md
coralogix-eventbridge-policy/template.yaml

https://coralogix.atlassian.net/browse/VTX-3815

Update aws eventbridge template to use role

---

coralogix-eventbridge-policy/CHANGELOG.md
coralogix-eventbridge-policy/README.md
coralogix-eventbridge-policy/template.yaml

https://coralogix.atlassian.net/browse/VTX-3815

Fix eventbridge description

---

scripts/replace_template.sh

[VTX-2948](https://coralogix.atlassian.net/browse/VTX-2948)
Updating parameters to track in the notification lambda to be consistent with their names `fields.yaml` file.
[VTX-2948]: https://coralogix.atlassian.net/browse/VTX-2948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update parameters to track in replace_template.sh script

---

coralogix-s3-archive/CHANGELOG.md
coralogix-s3-archive/template.yaml

Update the bucket permission role to the new one
Fixes #

Update the bucket role permissions [PLTD-478]

---

coralogix-eventbridge-policy/CHANGELOG.md
coralogix-eventbridge-policy/README.md
coralogix-eventbridge-policy/template.yaml

https://coralogix.atlassian.net/browse/VTX-3815

Add role name eventbridge

---

.github/workflows/synchronizing.yaml

Remove all of the deprecated integrations from the sync action
Fixes #

remove old integrations from the sync

---

.github/workflows/synchronizing.yaml
scripts/custom_lambda_code.yaml
scripts/replace_template.sh

Update the sync action to allow the template that it creates to retrieve secret value to use as apikey.
Add a new custom lambda that will retrieve the secret that contains the ApiKey and then the template will use this value to send the ApiKey to `integrations-custom-resource-notifier ` lambda. 
Fixes #

Update sync action to allow the created template to retrieve secrets

---

.github/workflows/synchronizing.yaml
scripts/replace_template.sh

Sync issue

---

aws-integrations/aws-shipper-lambda/template.yaml

trigger the sync action [CDS-1208]

---

.github/workflows/Changelog.yaml
.github/workflows/publish.yaml

Update actions version to avoid node.js 16 warning
Fixes #

update github action version[CDS-1221]

---

scripts/replace_template.sh

Update the sync code to handle templates that ends with outputs, also update the condition for each of the integration as each one has different parameters and conditions for CustomDomain
Fixes #

update the code for the sync action to work in case template has output section

---

.github/workflows/synchronizing.yaml

Update sync action to avoid vulnerability [INFOSEC-347]

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

Update URL for Us2

---

.github/workflows/synchronizing.yaml

Update sync action

---

aws-integrations/ecs-fargate/CHANGELOG.md
aws-integrations/ecs-fargate/README.md
aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

Updated example CloudFormation template to match the updated ECS Fargate integration
Deployed the CF as documented in the README.md, observed logs and metrics (No traces in demo) arriving at CX platform.

FEAT - Update CF for new ECS Fargate integration

---

coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-metrics-integration-policy/template.yaml

Add all the permissions we expect to need soon.
By using the same in enrichment lambda for firehose.

Add more permissions for metrics integration policy

---

coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-metrics-integration-policy/template.yaml

Fixes #
Depends on:
*  https://github.com/coralogix/gcp-collector/pull/863

Trust specific role

---

coralogix-policies/coralogix-metrics-integration-policy/README.md

Fix readme checked as part of the feature release.
@royfur @guyrenny FYI if you would be ever changing folders other documentation pointing to it would need to be updated soon.

Fix aws metrics policy readme

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

Add outputs section that will provide the role arn that the module creates
Fixes #

Add output for coralogix-metrics-integration-policy integration

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

New permissions for feature in progress for aws-metrics via cloudwatch integration
Locally with backend service

Add new permissions for rds enhanced monitoring

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

We need new permissions for ECS Enhanced monitoring.
Against AWS account.

New permission for ECS enhanced monitoring

---

coralogix-policies/coralogix-metrics-integration-policy/template.yaml

Small casing update to map used for AWS Metrics from CloudWatch integration
Fixes #
YAML has been linted.

policies: update Cx AWS metrics CFN template map

---

coralogix-policies/coralogix-eventbridge-policy/README.md
coralogix-policies/coralogix-metrics-integration-policy/README.md
coralogix-policies/coralogix-resource-catalog-role/README.md

Add to the policies integrations readme file a cli command to deploy the template

---

coralogix-policies/coralogix-resource-catalog-role/CHANGELOG.md
coralogix-policies/coralogix-resource-catalog-role/template.yaml

Add ec2:DescribeNetworkInterfaces LUM-451

---

aws-integrations/ecs-fargate/CHANGELOG.md
aws-integrations/ecs-fargate/README.md
aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

Added option for deploying with Advanced Parameter Store
Adjusted minimum permissions in Example CF template
Addresses: CDS-1599 and CDS-1614
Deployed to ECS Fargate cluster. Observed logs and metrics arriving from demo application.

[FEATURE] ECS-Fargate CF Advanced Parameter Store

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/README.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

Just fixing some typos and texts.
Fixes #

Fix aws metrics cloudformation texts

---

aws-integrations/ecs-fargate/CHANGELOG.md
aws-integrations/ecs-fargate/README.md
aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

Update ECS Fargate CF template with parameter store name that doesn't cause permission to be invalid.
Fixes CDS-1695
Deployed CF through AWS UI, deployed ECS Fargate task to existing ECS Cluster. Observed data arriving at CX.

[FIX] Small changes to ECS Fargate CF template

---

.github/workflows/synchronizing.yaml

Adjust the sync action for firehose-log to create the template under the shared folder
Fixes #

update sync action for firehose-logs

---

aws-integrations/ecs-fargate/CHANGELOG.md
aws-integrations/ecs-fargate/README.md
aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

parameter store configuration
Added Resource Catalog config to the Parameter Store.
Updated the Parameter Store name to not cause Access Policy error due to extra / character.
Deployed the CF template. Validated no errors in ECS Container logs. Observed Metrics and Logs (no traces from example container) into CX.

[FEAT] Add Resource Catalog config to ECS-Fargate OTEL

---

.github/workflows/Changelog.yaml
.github/workflows/publish.yaml
.github/workflows/synchronizing.yaml

Update tj-actions/changed-files version

---

coralogix-s3-archive/CHANGELOG.md
coralogix-s3-archive/README.md
coralogix-s3-archive/template.yaml

bug: fix typo

---

coralogix-policies/coralogix-infrastructure-explorer/CHANGELOG.md
coralogix-policies/coralogix-infrastructure-explorer/README.md
coralogix-policies/coralogix-infrastructure-explorer/template.yaml
coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/README.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

Do now allow empty external secret

---

.github/CODEOWNERS

Update CODEOWNERS to team-ido
