prometheus/ecs-ec2/autodiscovery/README.md
prometheus/ecs-ec2/autodiscovery/template.yaml

This PR adds an example template of setting up the Cloudwatch Agent to automatically detect prometheus scrape endpoints. It also adds a central prometheus scraper that scrapes all the detected endpoints.

[CDS-385] ECs-EC2 Prometheus Auto Discovery

---

coralogix-s3-archive/CHANGELOG.md
coralogix-s3-archive/README.md
coralogix-s3-archive/template.yaml

Add support to us2 region
Add variables:
* CustomCoraloigxArn - use to change the arn of the aws account id.
* ByPassRegion - use to bypass region restrictions.

Add support to us2 region and add CustomCoraloigxArn and ByPassRegion variables[CDS-552]

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/README.md
aws-integrations/firehose/template.yaml

Changes requested by @anatsyg to get our CF template.yaml aligned with integration team's one
- Template parameters ApplicationName and SubsystemName should be used for applicationNameDefault and subsystemNameDefault parameters for CoralogixDeliveryLogsStream [Firehose endpoint doc](https://coralogix.com/docs/aws-firehose/)
- Make the CloudWatchLogsRole name follow the next pattern '${AWS::StackName}-cloudwatchlogs’ and other rolesname + policynames too
- StackId instead of StackName for S3 bucket as stacknames can repeat
- CustomUrl to CustomDomain
Tested Locally on AWS account
Name changes mainly, mostly non-functional

Fix firehose integration alignment

---

.github/workflows/synchronizing.yaml
aws-integrations/lambda-integrations/resource-metadata/CHANGELOG.md
aws-integrations/lambda-integrations/resource-metadata/template.yaml

Add resource-metadata to sync github action.
https://coralogix.atlassian.net/browse/VTX-3068
The idea is to recreate this PR with a more updated version: https://github.com/coralogix/integration-definitions/pull/51
Would this change be enough to do that?

Add resource-metadata to sync github action

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

* Updated default ecs-ec2 default templates 
- removed  unnecessary OTEL_RESOURCE_ATTRIBUTES from default configuration  
- updated default `ecsattributes` config to include `docker.name`
- added resourcedetection for otel-collector metrics
- removed unnecssary differences between default and metric configurations

Update default ECS-EC2 Otel Config

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

Addes health_check extension to default otel ecs-ec2 configuration template.
Removed Default image from ecs-ec2 otel cfn template.

Add Healthcheck to ECS-EC2 default Otel config

---

aws-integrations/firehose/CHANGELOG.md
aws-integrations/firehose/template.yaml

Part of https://coralogix.atlassian.net/browse/ES-123.
Reflects the changes needed for migrating the runtime (for details see https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/).
This also has been reflected already in the transformation Lambda, see related change: https://github.com/coralogix/cloudwatch-metric-streams-lambda-transformation/pull/32
N/A

Migrate transformation Lambda runtime

---

.github/workflows/synchronizing.yaml

Split the `git checkout -b $branch_name` to branch and checkout separately.
also added `git fetch` lines.
Separate PR on separate branches, with the Gh Actions.

Gh Actions: fix for inability to do branch and checkout together

---

.github/workflows/Changelog.yaml
.github/workflows/synchronizing.yaml

actions/upload-artifact@v2 -> actions/upload-artifact@v3
actions/checkout@v2 -> actions/checkout@v3
gh-actions on separate branches

deprecation fix for annotation warning

---

.github/workflows/sync-coralogix-aws-shipper-cfn

This PR adds a workflow to sync changes to the cloudformation template made in the https://github.com/coralogix/coralogix-aws-shipper repo with this repo. The workflow can be triggered manually or via a github custom event.

Add Sync workflow for AWS Shipper Lambda repo

---

aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

Minor fix for otel-collector container SSM parameter name.
Change demo app to use open nginx container.
Follow instructions at https://coralogix.com/docs/aws-ecs-fargate/ 
Fixes error encountered when deploying the Task Definition:
```ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): invalid ssm parameters: config.yaml``` 
Error caused by incorrect SSM parameter path
Also uses nginx as demo container, serves port 80 without errors.

Fix ECS Fargate CloudFormation template ssm name, use nginx demo

---

.github/workflows/Changelog.yaml
.github/workflows/synchronizing.yaml

Sync action will now skip the create_pr job in case that a template that is not on the list has been changed
also update the changelog action to get trigger when there is a new label for the pr 
Fixes #

Update sync action to skip create_pr job instead of failing

---

prometheus/ecs-ec2/autodiscovery/CHANGELOG.md
prometheus/ecs-ec2/autodiscovery/README.md
prometheus/ecs-ec2/autodiscovery/template.yaml

This Pr removes the default image from the Promtheus Autodiscovery template.
Users must specify the image tag explicitly

Update Image Parameter for Prometheus Auto Discovery template

---

.github/workflows/publish.yaml
.github/workflows/synchronizing.yaml

Add workflow_dispatch to the sync and publish action, so in case there is an issue with github and the actions didn't get triggered we could trigger it manually using the commit
Fixes #

Add option to run the action manually

---

.github/workflows/publish.yaml
.github/workflows/synchronizing.yaml

The checkout action should get the files from the commit that is passing in case that you trigger manually, in other cases it will get the current files
Fixes #

Manual trigger bug fix for action publish and sync

---

coralogix-s3-archive/CHANGELOG.md
coralogix-s3-archive/template.yaml

Update the role for the metrics bucket, the new role `arn:aws:iam::${aws_account_id}:role/coralogix-archive-${aws_role_region}` is working right now only for logs and not metrics

S3 archive update role for metrics bucket [CDS-982]

---

.github/workflows/synchronizing.yaml

In integration-definition the aws-shipper-lambda is now under the shared folder so i have update the sync to create the new template under the shared folder
Fixes #

move the aws-shipper lambda in the sync to shared folder

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

- [cds-724] re-add sync workflow (#10)  * initial commit
* Example of receiving the S3 payload
* newline_pattern
* sending to coralogix
* sending as batch
* Put records in ExportLogsServiceRequest
* sent to coralogix working
* added gzip at source
* Limit batch size to 500 logs
* Adding integration_type
* Implement splitting with fancy regexes
* WIP Blocking Pattern
* Blocking Working
* wip sampling blocking_pattern
* WIP DynamicAppName
* WIP dyn app
* Dynamic application/subsystem name
* added cloudtrail support WIP
* Cloudwatch working
* WIP Severity
* Severity fix
* Severity Matcher
* Resource per app/subsystem
* git ignored cargo.lock
* cloudtrail working
* initial sns
* sns working
* Working SNS
* Split initial
* Split initial
* vpcflow working
* Cloudwatch work in progress
* …

fix mount ecs ec2

---

coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-metrics-integration-policy/README.md
coralogix-metrics-integration-policy/template.yaml

Created a new module that will create a role, the role will allow: tag:GetResources, cloudwatch:GetMetricStatistics, cloudwatch:ListMetrics to all resource.
The role will have trusting relationship with the AWS account that the user will choose using the `AWSAccount` or `CustomeAccountId`
Fixes #

new module that will create role that will be used my metrics integration [CDS-1155]

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

Removes deprecated ecs-ec2 cfn template param

Remove ECS-EC2 Deprecated cfn template parameter

---

coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-metrics-integration-policy/template.yaml

We are using new API to fetch metrics.
We need one more permission, because we use one more API for getting metrics.
I have added better logging and it now fails on missing access in the integration.

Update cloudwatch metric integrations rights

---

aws-integrations/firehose-metrics/CHANGELOG.md
aws-integrations/firehose-metrics/README.md
aws-integrations/firehose-metrics/template.yaml

default metrics type set as CloudWatch_Metrics_OpenTelemetry070_WithAggregations
Locally

set metrics type aggregations as default

---

coralogix-s3-archive/CHANGELOG.md
coralogix-s3-archive/template.yaml

Add delete permissions to the bucket rule, and update ap1 and ap2 regions in the mapping:
ap1: ap-south-1
ap2: ap-southeast-1
Fixes #

Add more permissions to archive for delete, and interchanged ap1 and ap2 regions [FASTV2-1262]

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

Due to config changes in upstream otel, `--config <value>` flags are now being enforced explicitly, even though the value in our case is read from the ENV variable.
- Added command to task definition: `--config env:OTEL_CONFIG`

cds-1304 Added Command Flag to ECS-EC2 otel task definition

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

- Adjusted how ENV variables are set in the ECS-EC2 embedded otel config,`$VAR` has been deprecated in favor of `${VAR}`
- Updated README to reflect that as of `v0.3.0` decoding base64 encoded env variables is not supported.
- Added `account-` prefix to account ID default subsystem name in embedded otel config to fix issue with this value being interpreted as a float during unmarshalling in otel.

Update ENV Vars in embedded Otel Config

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

New permission to be able to get RDS and EC2 instance metadata like allocated memmory, CPU, etc.
In aws UI

Another permission for RDS enhanced monitoring

---

coralogix-policies/coralogix-metrics-integration-policy/CHANGELOG.md
coralogix-policies/coralogix-metrics-integration-policy/template.yaml

Fix permission name in the metrics integration policy.
Fixes #163

Fix rds:ListTagsForResource permission name

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/template.yaml

in the middle of my ECS/EKS onboarding tests, and I've found the bug that's causes the default otel config failing
```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'receivers': error reading configuration for "filelog": 1 error(s) decoding:
* error decoding 'operators[1]': unmarshal to json_parser: 1 error(s) decoding:
* '' has invalid keys: default
```
otelcol claims that the json_parser operator doesn't have the default option/key, and it doesn't start because of it – in fact, it's right, because there is no such option, as I see in [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/json_parser.md)
router operator has this key, but json_parser doesn't
once I removed this …

fix: ECS-EC2 Remove breaking line from otelcol config

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

ECS EC2 integration was rewritten with _**breaking changes**_ to support Parameter Store custom configurations.
ECS EC2 integration had new pipelines added and tweaked, including Resource Catalog support.
Deployed to ECS cluster with workload task definition running in parallel. Observed logs, metrics and traces arriving at CX.

Ecs ec2 update - CDS-1735

---

aws-integrations/ecs-fargate/CHANGELOG.md
aws-integrations/ecs-fargate/ecs-fargate-cf.yaml

Added Head Sampling (probabilistic_sampler) with default sampling of 10% and default proportional mode and new variables to disable it or update sampling values.
[CDS-1971](https://coralogix.atlassian.net/browse/CDS-1971)
Deployed the otel agent with default settings, deployed using updated settings, deployed using disabled setting.
[CDS-1971]: https://coralogix.atlassian.net/browse/CDS-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[feat]: Added head sampling to fargate ECS-EC2 integration CDS-1971 

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

Added Head Sampling (probabilistic_sampler) with default sampling of 10% and default proportional mode and new variables to disable it or update sampling values.
[CDS-1971](https://coralogix.atlassian.net/browse/CDS-1971)
Deployed the otel agent with default settings, deployed using updated settings, deployed using disabled setting.
[CDS-1971]: https://coralogix.atlassian.net/browse/CDS-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[feat] Add head sampling to ecs ec2 cloudformation cds-1971

---

aws-integrations/firehose-logs/CHANGELOG.md
aws-integrations/firehose-logs/template.yaml
aws-integrations/firehose-metrics/CHANGELOG.md
aws-integrations/firehose-metrics/template.yaml

Related to these two
* https://github.com/coralogix/terraform-coralogix-aws/pull/229
* https://github.com/coralogix/documentation/pull/681
No need to test allowed values are 1 to 64MiB
Open question, we add versions just in changelog and that is it @coralogix/team-cs-devops realised it only now that I never did more in this repo.

[firehose-logs|metrics] Normalize buffering hints with TF and docs

---

opentelemetry/ecs-ec2-windows/template.yaml

Update windows cloudformation template, removed base64 encoding as it is not supported and modified logging exporter.

fix: remove base64 encode from windows otel_config

---

opentelemetry/ecs-ec2-windows/CHANGELOG.md
opentelemetry/ecs-ec2-windows/README.md
opentelemetry/ecs-ec2-windows/template.yaml
opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/template.yaml

Added healthcheck parameter and its properties to the template.
The healthcheck is using a binary added to coralogix otel that can be called by the ECS task.
[CDS-2147](https://coralogix.atlassian.net/browse/CDS-2147)
- I have updated the relevant component changelog(s)
[CDS-2147]: https://coralogix.atlassian.net/browse/CDS-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEAT] - Add support for new healthcheck binary in coralogix otel CDS-2147

---

opentelemetry/ecs-ec2/CHANGELOG.md
opentelemetry/ecs-ec2/README.md
opentelemetry/ecs-ec2/examples/comprehensive-config.yaml
opentelemetry/ecs-ec2/template.yaml

Parameter store has a character limit which prevent using any otel config, so added s3 provider support.
- Reorganise the cloud formation parameters order.
- Added a selector for otel conf as template/s3/Parameter-Store.
- TaskRoleARN is created on the fly for both s3 and parameter store.
- Added a complete example file for s3.
- Updated Readme 
- [x ] I have updated the relevant component changelog(s)

Add support for s3 provider to read otel configuration file

---

aws-integrations/aws-shipper-lambda/CHANGELOG.md
aws-integrations/aws-shipper-lambda/README.md
aws-integrations/aws-shipper-lambda/template.yaml

Added a new create_sns_topic_policy variable to the coralogix-aws-shipper module to allow users to preserve existing SNS topic policies when using SNS-based integrations. This addresses the issue where the module would overwrite custom SNS topic policies with its own restrictive policy.
The variable defaults to true (maintaining backward compatibility) but can be set to false to prevent the module from creating or managing SNS topic policies, allowing users to maintain their own custom policies.
- [ v I have updated the relevant component changelog(s)

fix(coralogix-aws-shipper): add option to preserve custom sns policies
